development:
  default: &default  
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  schema_search_path: public,extensions

development:
  <<: *default
  database: travel_development
  username: spp_user
  password: admin